### ISSUE TITLE
안 되는 책 발견 - Chaos Engineering 

### ISSUE THREAD

**Issue by deulkkae** [anemochore/oreillyHack#5]
`fetching 3 chapter htmls... see console for the detail.
VM193:375 Uncaught (in promise) TypeError: Cannot read property 'innerText' of null
    at <anonymous>:375:50
    at NodeList.forEach (<anonymous>)
    at <anonymous>:372:23
    at Array.forEach (<anonymous>)
    at sectTitleNumbering (<anonymous>:368:49)
    at parseBody (<anonymous>:281:7)
    at mergeChapters (<anonymous>:150:20)
    at safari_dl.main (<anonymous>:89:5)
(anonymous) @ VM193:375
(anonymous) @ VM193:372
sectTitleNumbering @ VM193:368
parseBody @ VM193:281
mergeChapters @ VM193:150
main @ VM193:89
async function (async)
main @ VM193:88
(anonymous) @ VM190:1
async function (async)
(anonymous) @ VM190:1
(anonymous) @ VM190:1`

도서 링크: https://learning.oreilly.com/library/view/chaos-engineering/9781492043850/

**Comment by deulkkae** [comment]
오라일리에서 데이터 업데이트 후 다운로드가 잘 됨.

**Comment by anemochore** [comment]
얼리 액세스 도서는 챕터가 전부 없거나 해서 제대로 동작하지 않곤 합니다.
