### ISSUE TITLE
에러 [Infrastructure as Code, 2nd Edition]

### ISSUE THREAD

**Issue by deulkkae** [anemochore/oreillyHack#7]
https://learning.oreilly.com/library/view/infrastructure-as-code/9781098114664/

![image](https://user-images.githubusercontent.com/59636650/103333692-1280d800-4ab2-11eb-84ec-5cc420f5c24d.png)

**Comment by anemochore** [comment]
제가 전에 수정을 잘못했네요. 고쳐놨습니다. 
https://github.com/anemochore/oreillyHack/commit/8582201c95228b84777f2c98174dcd67902df03a#diff-9fddb4fd085f6c7492f29f669487406909a017a0fd23273aceb603756129e970
